### ISSUE TITLE
TypeScript optional indicator for parameter/properties not reflected in type

### ISSUE THREAD

**Issue by Niznikr** [open-wc/custom-elements-manifest#102]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**
When using the `?` operator in TypeScript to indicate an [optional property](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#optional-parameters-and-properties), I would expect the type to be `propType | undefined`. In this [playground example](https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7IExpdEVsZW1lbnQgfSBmcm9tICdsaXQtZWxlbWVudCc7CmltcG9ydCB7IHByb3BlcnR5IH0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnOwoKZXhwb3J0IGNsYXNzIE15RWxlbWVudCBleHRlbmRzIExpdEVsZW1lbnQgewogIEBwcm9wZXJ0eSh7IHR5cGU6IFN0cmluZywgcmVmbGVjdDogdHJ1ZSB9KQogIHB1YmxpYyBmb28%2FOiBzdHJpbmc7CgogIG15TWV0aG9kKCl7fQp9Cg%3D%3D&library=litelement) I would expect the type for `foo` to be `string | undefined` instead of `string`.

**Comment by thepassle** [comment]
This should be fixed in #106
