### ISSUE TITLE
How to handle private class fields

### ISSUE THREAD

**Issue by jpzwarte** [open-wc/custom-elements-manifest#111]
Currently If you have a class with private class fields, cem outputs those fields.

```javascript
class Foo {
  #bar = 'bar';
}
```

Example cem output (from another lit element web component):

```json
            {
              "kind": "field",
              "name": "#initials",
              "privacy": "private",
              "type": {
                "text": "string | undefined"
              },
              "description": "The actual initials shown in the UI. We keep this as a separate variable to determine\nwhether the initials are derived from the displayName or explicitly set via the initials property."
            },
```

Unlike typescript `private` keyword fields, private class fields are *really* private. So trying to access `foo.#bar` results in a syntax error.

Since you cannot access these private class fields from outside the class, should cem really output these fields?

**Comment by thepassle** [comment]
I think this might be a discussion to have in the schema standardization repo https://github.com/webcomponents/custom-elements-manifest

**Comment by thepassle** [comment]
Documenting 'true' private members may not be useful for consumers of your component, but it can be useful to document them for internal use/colleagues who are working on the component. 

Since this is more of a discussion on the schema itself, i'll close this issue here
