### ISSUE TITLE
Improved TypeScript ergonomics

### ISSUE THREAD

**Issue by bennypowers** [open-wc/custom-elements-manifest#12]
This issue tracks some nice-to-have enhancements for type detection.

The analyzer does great picking up on explicitly typed members:

```ts
function XMixin<B extends Constructor<{ b: B }>(superclass: B) {
  return class XL<A> extends superclass {
    x: X<A> = new X<A>(this.b);
    bool: boolean = true;
  }
}
```

Here,
- the mixin parameter will be correctly typed as `B`
- the `x` field will be correctly typed as `X<A>`
- the `bool` field will be typed as `boolean`

However, it would be nice if for the following code:

```ts
function XMixin<B extends Constructor>(superclass: B) {
  return class XL<A> extends superclass {
    x = new X<A>();
    bool = true;
  }
}
```

Would give:
- the parameter as `B extends Constructor<{ b: B }>`
- the `x` field as `X<A>` (even without an explicit typing)
- the `bool` field as `boolean` (even without an explicit typing)

I'm guessing that the TypeScript API has the chops to infer those things, given a `SourceFile` AST, but I haven't looked into it just yet.

**Comment by bennypowers** [comment]
I've got a plugin for boolean types, want that in core?

**Comment by thepassle** [comment]
What does the plugin do exactly? Assign the type of `bool` to be `{type: {text: boolean}}` by inferring the type from its default value?

I think we could add some type inference behavior for fields, (and variables?), but we'd need to make sure to keep the correct 'priority' of type systems. Currently JSDoc will overrule TS types, so the priority should probably be (from least prio to highest prio):

- inferred type
- TS type (overrules inferred)
- JSDoc type (overrules TS)

**Comment by bennypowers** [comment]
I'll open a draft PR and we can go over it there 🙂

**Comment by thepassle** [comment]
I think we should make a new handler for this, something like `handleTypeInference` and add it here: https://github.com/open-wc/custom-elements-manifest/blob/master/packages/analyzer/src/features/analyse-phase/creators/createClassField.js#L18

```js
fieldTemplate = handleTypeInference(fieldDoc, node);
```

That way we can easily add it for variables as well

**Comment by thepassle** [comment]
type inference was added, ill close this for now
