### ISSUE TITLE
Add a CLI/config entry to prevent CEM/A from writing to a package.json file

### ISSUE THREAD

**Issue by Westbrook** [open-wc/custom-elements-manifest#121]
**Expected behavior**
Running the analyzer will only write to my `package.json` when I want it to.

**CLI/config entry options***
So as not to make this change breaking, we likely want a negation style flag here. Some options for review:
```
cem analyze --no-package-json
cem analyze --no-linking
cem analyze --create-only
cem analyze --packagejson=false // defaulting to true
... more?
... better?
```
With my naive though that these kabob case flags would move to camel case in a config file.

Thoughts?

**Comment by thepassle** [comment]
this should be fixed in #142
