### ISSUE TITLE
Question: How do you generate descriptions?

### ISSUE THREAD

**Issue by hasanirogers** [open-wc/custom-elements-manifest#122]
Got the tool to work with my project that uses LitElement components. I don't see anything that documents how to generate descriptions though. Can someone point me in the right direction here?

**Comment by thepassle** [comment]
You can use jsdoc to add descriptions, see example [here](https://custom-elements-manifest.netlify.app/?source=Ci8qKgogKiBIZWxsbyBJIGFtIGEgZGVzY3JpcHRpb24KICovCmNsYXNzIE15RWxlbWVudCBleHRlbmRzIEhUTUxFbGVtZW50IHsKICBzdGF0aWMgZ2V0IG9ic2VydmVkQXR0cmlidXRlcygpIHsKICAgIHJldHVybiBbJ2Rpc2FibGVkJ107CiAgfQoKICAvKioKICAgKiBJIGFtIGEgZGVzY3JpcHRpb24gdG9vCiAgICovCiAgc2V0IGRpc2FibGVkKHZhbCkgewogICAgdGhpcy5fX2Rpc2FibGVkID0gdmFsOwogIH0KICBnZXQgZGlzYWJsZWQoKSB7CiAgICByZXR1cm4gdGhpcy5fX2Rpc2FibGVkOwogIH0KCiAgLyoqCiAgICogQW5kIEkgYW0gYSBkZXNjcmlwdGlvbiBhcyB3ZWxsCiAgICovCiAgZmlyZSgpIHsKICAgIHRoaXMuZGlzcGF0Y2hFdmVudChuZXcgRXZlbnQoJ2Rpc2FibGVkLWNoYW5nZWQnKSk7CiAgfQp9CgpjdXN0b21FbGVtZW50cy5kZWZpbmUoJ215LWVsZW1lbnQnLCBNeUVsZW1lbnQpOwo%3D&library=null)
