### ISSUE TITLE
Error: UNKNOWN_VALUE: Unknown value: CustomElement.js

### ISSUE THREAD

**Issue by baermathias** [open-wc/custom-elements-manifest#153]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?

I have tried to run the analyzer on one of the `lion` components. Summary steps of what I did:

```bash
npm install -g @custom-elements-manifest/analyzer
git clone https://github.com/ing-bank/lion.git
cd lion
cem analyze packages/button/src/LionButton.js --litelement
```

This gives me the following error:

```
/Users/username/.nvm/versions/node/v16.13.0/lib/node_modules/@custom-elements-manifest/analyzer/node_modules/command-line-args/dist/index.js:1345
        const err = new Error(`Unknown value: ${arg}`)

UNKNOWN_VALUE: Unknown value: packages/button/src/LionButton.js
    at commandLineArgs (/Users/username/.nvm/versions/node/v16.13.0/lib/node_modules/@custom-elements-manifest/analyzer/node_modules/command-line-args/dist/index.js:1345:21)
```

Do I miss something?

**Expected behavior**
Create a manifest file.

**Comment by thepassle** [comment]
You have to use the `--globs` flag to specify which files you want to analyze. See https://custom-elements-manifest.open-wc.org/analyzer/config/#config-file
