### ISSUE TITLE
Custom element tag name not contained in the manifest

### ISSUE THREAD

**Issue by sanjatasic** [open-wc/custom-elements-manifest#158]
**Checklist**
- [] Did you run the analyzer with the `--dev` flag to get more information?
- [] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**
Would expect a custom element tag name to be included in the manifest. What is the reason that this is not the case?

**Comment by thepassle** [comment]
I dont know

**Comment by sanjatasic** [comment]
Should this question be asked in the JSON schema spec project?

**Comment by thepassle** [comment]
Probably not. But you didnt make a minimal reproduction in the playground (like it says in the issue template that you edited), so there's no way for me to know whats going on.

**Comment by sanjatasic** [comment]
Sorry, my bad.
Did not create minimal reproduction in the playground, but did run the analyzer with --dev flag, as suggested.

Here is custom element class:
`import { LitElement, TemplateResult, html } from "lit";
import { customElement, property } from "lit/decorators.js";

/**
 * @CustomElement my-element
 */
@customElement("my-element")
export default class MyElement extends LitElement {
  @property({
    type: Boolean,
  })
  disabled: boolean = false;

  // eslint-disable-next-line class-methods-use-this
  render(): TemplateResult {
    return html`<div></div>`;
  }
}
`
Command executed:
`cem analyze --globs src/my-element.ts --litelement --dev`

Output:
`[PACKAGE LINK PHASE]
{
  "schemaVersion": "1.0.0",
  "readme": "",
  "modules": []
}
[9:32:20 AM] @custom-elements-manifest/analyzer: Created new manifest.`

But in the meantime figured out, that probably support for Lit decorators (at least the @customElement one) is still not implemented...

**Comment by thepassle** [comment]
The analyzer supports Lit, and its decorators. Did you run the analyzer with special handling for Lit enabled? e.g. `cem analyze --litelement`

Please make sure to thoroughly read the documentation and issue template before creating an issue https://custom-elements-manifest.open-wc.org/

**Comment by sanjatasic** [comment]
I did, with the same result
