### ISSUE TITLE
Programmatically invoke the analyzer

### ISSUE THREAD

**Issue by Poliziano** [open-wc/custom-elements-manifest#162]
Hi - it is possible to invoke the analyzer from within TypeScript/JavaScript? I have a Vite plugin that I'm working on that produces the manifest during a build. I'm currently use `child_process` to the invoke the command which works fine, but preferably I would be able to directly call the analyzer. Is this reasonable/possible to do? Thanks!

**Comment by thepassle** [comment]
Yes, you can read more about there: https://custom-elements-manifest.open-wc.org/analyzer/getting-started/#usage-in-the-browser

The title says "usage in the browser", but the usage is the same in Node

**Comment by thepassle** [comment]
Thats because this package is `"type": "module"`

More info:
https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1
