### ISSUE TITLE
generate WEBCOMPONENTS.md or update WEBCOMPONENTS section of README.md

### ISSUE THREAD

**Issue by sashafirsov** [open-wc/custom-elements-manifest#164]
This is enhancement proposal which could be implemented as independent CLI or part of `cem`. 

In projects often README.ms serves API and web component attributes/events definition. Keeping this section up-to-date is difficult manual task and as manual not prone for errors. Generation of MD section either from code or from manifest would keep the ts/js code as source of truth.

Similar could be achieved by the JSDoc cli and embedding the htlm into MD by `sed` in single command line. But JSDoc is not web components tuned and not meant to fit into README.md conventions.

**Comment by sashafirsov** [comment]
found [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown) as fast work around. 

CONS: web component specific presentation as in markdown is missing.

**Comment by thepassle** [comment]
Im not really sure what this issue is about. I dont see a proposal for an enhancement?

We do have tools to generate markdown. Did you see https://github.com/open-wc/custom-elements-manifest/tree/master/plugins/readme?

**Comment by sashafirsov** [comment]
Sweet, I was not aware of that package, thank you.

Closing this proposal in favor of [custom-elements-manifest](https://github.com/open-wc/custom-elements-manifest)
