### ISSUE TITLE
Vitejs plugin

### ISSUE THREAD

**Issue by EmilienLeroy** [open-wc/custom-elements-manifest#168]
Hello 😄

I have developed a little plugin for [Vite.js](https://vitejs.dev/) using the [@custom-elements-manifest/analyzer](https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer) to build the custom elements manifest on the fly. I think it can be interesting for some peoples to use it but I don't know if it can be added into the [community plugins](https://custom-elements-manifest.open-wc.org/analyzer/plugins/intro/#community-plugins) because it's vitejs plugin and not cem-plugin. Can I open a PR adding the link of my plugin into your documention ?

You can find the repository of the plugin here: https://github.com/Kamiapp-fr/vite-plugin-cem

**Comment by thepassle** [comment]
Sure! Feel free to make a PR

Cool plugin 🙂

**Comment by thepassle** [comment]
fixed via #169

**Comment by EmilienLeroy** [comment]
@thepassle Thanks you ! 😄
