### ISSUE TITLE
update included typescript version

### ISSUE THREAD

**Issue by KingOfTac** [open-wc/custom-elements-manifest#211]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [ ] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

Currently, it looks like the analyzer is using typescript@4.3.2 internally. AST Explorer now uses typescript@4.7.4 which has made developing plugins a bit difficult due to typescript internal interfaces changing across versions. An example of this is in the `SyntaxKind` enum. In AST Explorer a node kind of 237 is a `VariableStatement` and in the analyzer it is a `WhileStatement`.

**Comment by thepassle** [comment]
yeah you shouldnt really check for SyntaxKind like that I dont think, you should use the methods provided by TS, like `ts.isStringLiteral` etc

**Comment by KingOfTac** [comment]
> yeah you shouldnt really check for SyntaxKind like that I dont think, you should use the methods provided by TS, like `ts.isStringLiteral` etc

Makes sense, thanks. One other thing I have run up against with the version bundled with the analyzer is that it looks like it doesn't associate jsDoc comments with variable declarations while newer versions of the language do.
