### ISSUE TITLE
command fails with "Unexpected token '.'"

### ISSUE THREAD

**Issue by Lord-Leonard** [open-wc/custom-elements-manifest#222]
**Description**
When I run the command the generate the manifest the programm fails, stating the following: 

```bash
PS C:\..\slottedComponentsTest> custom-elements-manifest analyze
file:///C:/../slottedComponentsTest/node_modules/@custom-elements-manifest/analyzer/cli.js:44
      const modules = userConfig?.overrideModuleCreation
                                 ^

SyntaxError: Unexpected token '.'
```

I am a little los here as to why it doesn't work. 
Is there any configuration I need to do before using the command inside my root direktory?

**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [ ] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

**Expected behavior**
The command should generate the json file...

**Comment by thepassle** [comment]
which version of node are you using? It looks like your version of node doesnt support optional chaining

**Comment by Lord-Leonard** [comment]
ahhhhhh fuck 
sorry, yeah i should have checked that, I am currently stuck at 12. 
well what a schame :(
