### ISSUE TITLE
HOWTO pass custom cli arguments to `analyze` that a plugin can work on?

### ISSUE THREAD

**Issue by LorenzKahl** [open-wc/custom-elements-manifest#223]
In my custom CEM plugin I would like to generate a different output for prod / dev environments.

I tried calling the analyzer providing a custom argument `environment`:
```bash
cem analyze --litelement --environment="production"
```

But it fails with the following error:
`> Uncaught UNKNOWN_OPTION: Unknown option: --environment`

Is there a better way to achieve this that I am missing?

**Comment by thepassle** [comment]
You can use `process.env` for this, e.g.:

```
FOO=BAR cem analyze
```

And then in your plugin you can do:
```js
if(process.env.FOO === 'bar') {}
```
