### ISSUE TITLE
Programmatic JS API instead of CLI, How-to?

### ISSUE THREAD

**Issue by JulianCataldo** [open-wc/custom-elements-manifest#229]
Hello!

Is there an "official" way of using the analyzer via a JS API? Or should we import the `cli` function and pass the `argv` ourselves?

Thanks you for you work :)

**Comment by thepassle** [comment]
You can use it like this in node as well: https://custom-elements-manifest.open-wc.org/analyzer/getting-started/#usage-in-the-browser
