### ISSUE TITLE
Analyzer error when extending a mixin with a typescript type param

### ISSUE THREAD

**Issue by matteematt** [open-wc/custom-elements-manifest#231]
**Checklist**
- [X] Did you run the analyzer with the `--dev` flag to get more information?
- [ ] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)? - doesn't crash on there for some reason

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**

The analyzer is crashing in the analyze phase when there is a class that extends a mixin, where the mixin parameter is a class with a typescript type param
```
export class A extends MixinFn(B<C>) {}
```

See gif 
![analyzer_error](https://github.com/open-wc/custom-elements-manifest/assets/43502076/c764bfd5-00b6-4477-bb04-58913167334a)

**Comment by thepassle** [comment]
Im unable to reproduce, please provide a reproduction in the playground as mentioned in the issue template.

**Comment by DRiFTy17** [comment]
@thepassle I was running into this for a while as well, but just updated to `0.10.2` and it's working fine for me now so I think we're all set. I narrowed it down to a change between `0.9.3` (not working) and `0.9.4` (working) in case anyone else runs into this one.

**Comment by thepassle** [comment]
Thanks for confirming 👍

**Comment by matteematt** [comment]
@DRiFTy17 thanks, I was struggling to recreate it locally and wasn't able to, and didn't have much time to dig into it. I guess it was because it was fixed. Thanks!
