### ISSUE TITLE
Type annotations on a (lit) property are ignored if the property has a default value

### ISSUE THREAD

**Issue by rstoneIDBS** [open-wc/custom-elements-manifest#234]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

[Playground Reproduction](https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7IExpdEVsZW1lbnQgfSBmcm9tICdsaXQtZWxlbWVudCc7CgpleHBvcnQgY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7CiAgc3RhdGljIGdldCBwcm9wZXJ0aWVzKCkgewogICAgcmV0dXJuIHsKICAgICAgLyoqCiAgICAgICAqIEB0eXBlIHsnb25lJyB8ICd0d28nfQogICAgICAgKi8gIAogICAgICBmb286IHsgdHlwZTogU3RyaW5nIH0sCgogICAgICAvKioKICAgICAgICogQHR5cGUgeyd0aHJlZScgfCAnZm91cid9CiAgICAgICAqLyAgCiAgICAgIGJhcjogeyB0eXBlOiBTdHJpbmcgfQogICAgfQogIH0KCiAgY29uc3RydWN0b3IoKSB7CiAgICBzdXBlcigpOwogICAgdGhpcy5mb28gPSAnaGVsbG8nOwogIH0KCiAgbXlNZXRob2QoKXt9Cn0K&library=litelement)

**Expected behavior**
In the playground example, I would expect the type for the ``foo`` property to be:
```
"type": {
  "text": "'one' | 'two'"
}
```

I did experiment with trying to force the type of the default value via JSDoc comments but this didn't change the output

**Comment by rstoneIDBS** [comment]
And then I tried again :)

Adding:
```
  constructor() {
    super();
    /** @type {'one' | 'two'} */   
    this.foo = 'hello';
  }
```

gets it working, however I wonder if this is still an issue, i.e. having the types declared with the properties feels much nicer than having to spread them around into constructors too

**Comment by thepassle** [comment]
Yeah, that wont work; for TS that won't work either, because TS is not aware that the properties defined in `static properties` will get turned into actual class properties by lit internally. You could write a custom plugin to support this, but I doubt we'll support this in core

**Comment by rstoneIDBS** [comment]
Yup - just bumped into the TS thing not working too :( TS aside, then you say it "won't work" - why does it work for the 'bar' property that doesn't have a default value?
