### ISSUE TITLE
Wrong parse Object from AST

### ISSUE THREAD

**Issue by next-juanantoniogomez** [open-wc/custom-elements-manifest#239]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7IExpdEVsZW1lbnQgfSBmcm9tICdsaXQtZWxlbWVudCc7CgpleHBvcnQgY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7CiAgc3RhdGljIGdldCBwcm9wZXJ0aWVzKCkgewogICAgcmV0dXJuIHsKICAgICAgICAvKioKICAgICAgICAgKiBGb28gdmFsdWUKICAgICAgICAgKiBAZGVmYXVsdCB7IGZvbzogJ2JhcicgfQogICAgICAgICAqLwogICAgICAgIGZvbzogeyB0eXBlOiBPYmplY3QgfQogICAgfQogIH0KCiAgY29uc3RydWN0b3IoKSB7CiAgICBzdXBlcigpOwoKICAgIC8vICdkZWZhdWx0JyB2YWx1ZSBzaG91bGQgYmUgInsgZm9vOiAnYmFyJyB9IiAoSlNPTi1zdHJpbmdpZmllZCksCiAgICAvLyBub3QgIntcbiAgICAgICAgZm9vOiAnYmFyJ1xuICAgIH0iCiAgICB0aGlzLmZvbyA9IHsKICAgICAgICBmb286ICdiYXInCiAgICB9OwogIH0KCiAgbXlNZXRob2QoKXt9Cn0K&library=litelement)?

**Expected behavior**

I have a Lit component (no Typescript) and the constructor assigns a default value to a property. If the value is an object, it is parsed as String instead of Object:

```js
  constructor() {
    super();

    // In the manifest, 'default' value should be "{ foo: 'bar' }" (JSON-stringified),
    // not "{\n        foo: 'bar'\n    }"
    this.foo = {
        foo: 'bar'
    };
  }
```

```json
"members": [
  {
    "kind": "method",
    "name": "myMethod"
  },
  {
    "kind": "field",
    "name": "foo",
    "privacy": "public",
    "type": {
      "text": "object"
    },
    "description": "Foo value",
    "default": "{\n        foo: 'bar'\n    }",
    "attribute": "foo"
  }
],
"attributes": [
  {
    "name": "foo",
    "type": {
      "text": "object"
    },
    "description": "Foo value",
    "default": "{\n        foo: 'bar'\n    }",
    "fieldName": "foo"
  }
],
```

In the [AST explorer](https://astexplorer.net/#/gist/b7ad20b26ea64154038d78cf66140079/latest), the object appears as ObjectLiteralExpression, so it could be proccessed as Object.

**Comment by thepassle** [comment]
this should be fixed in 0.10.1
