### ISSUE TITLE
Support for ElementInternals state

### ISSUE THREAD

**Issue by KonnorRogers** [open-wc/custom-elements-manifest#246]
Would it be possible to add a tag for `@state` to document CSS Custom States?

**Comment by thepassle** [comment]
Can you elaborate/show some examples/documentation?

**Comment by KonnorRogers** [comment]
@thepassle 

```js
/** 
 * @state open - When the element is open
 */
class MyEl extends HTMLElement {
  constructor () {
    super()
    this.internals = this.attachInternals()
  }

  open () {
    this.internals.states.add("open")
  }
}
```

Example of CSS Custom states:

```css
my-el { display: none; }

my-el:state(open) {
  display: block;
}
```

Also open to `@customState` since `@state` can be confused with the decorator from Lit

**Comment by thepassle** [comment]
I think we should go with `@csscustomstate` or `@cssstate` to align with `@csspart` and `@cssproperty`

**Comment by KonnorRogers** [comment]
Works for me.

`@cssstate` scared me because it seems really easy to typo.

**Comment by thepassle** [comment]
because its not consistent with `@csspart` and `@cssproperty`
