### ISSUE TITLE
[Analyzer] Symbols used as property keys crash the analyzer

### ISSUE THREAD

**Issue by rkaraivanov** [open-wc/custom-elements-manifest#264]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

**Expected behavior**
The analyzer successfully runs to completion.

**Actual behavior**
The analyzer crashes when a symbol in encountered during the analyzing phase.

![image](https://github.com/open-wc/custom-elements-manifest/assets/20106115/53f650c9-5698-40de-a976-d84d08491a96)

# Playground issue

[Reproduction URL](https://custom-elements-manifest.netlify.app/?source=CmV4cG9ydCBjb25zdCBfdGhlbWUgPSBTeW1ib2woKTsKCmNsYXNzIE15RWxlbWVudCBleHRlbmRzIEhUTUxFbGVtZW50IHsKICBzdGF0aWMgZ2V0IG9ic2VydmVkQXR0cmlidXRlcygpIHsKICAgIHJldHVybiBbJ2Rpc2FibGVkJ107CiAgfQoKICBnZXQgW190aGVtZV0oKSB7CiAgICAgIHJldHVybiAnbXktdGhlbWUnOwogIH0KCiAgc2V0IGRpc2FibGVkKHZhbCkgewogICAgdGhpcy5fX2Rpc2FibGVkID0gdmFsOwogIH0KICBnZXQgZGlzYWJsZWQoKSB7CiAgICByZXR1cm4gdGhpcy5fX2Rpc2FibGVkOwogIH0KCiAgZmlyZSgpIHsKICAgIHRoaXMuZGlzcGF0Y2hFdmVudChuZXcgRXZlbnQoJ2Rpc2FibGVkLWNoYW5nZWQnKSk7CiAgfQp9CgpjdXN0b21FbGVtZW50cy5kZWZpbmUoJ215LWVsZW1lbnQnLCBNeUVsZW1lbnQpOwo%3D&library=vanilla)

## Additional information:
This used to work in versions <= 0.9.9

**Comment by thepassle** [comment]
Fixed in 0.10.3
