### ISSUE TITLE
Circular reference when converting to JSON schema

### ISSUE THREAD

**Issue by p-ob** [open-wc/custom-elements-manifest#30]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

In writing a custom element to render custom elements manifest in a friendly format, we've encountered an issue when trying to generate the custom element manifest for this component.

I've included a txt file at the end so I could identify the cyclical items in the object that is being passed to `JSON.stringify`

We're using latest of lit (2.0.0-rc.2) and TypeScript 4.3.4. 

<details><summary>Output</summary>
[COLLECT PHASE]:  src/ce-schema-viewer.ts
[ANALYZE PHASE]:  src/ce-schema-viewer.ts
[MODULE LINK PHASE]:  src/ce-schema-viewer.ts
[PACKAGE LINK PHASE]
Waiting for the debugger to disconnect...
file:///C:/code/zywave/custom-element-viewer/node_modules/@custom-elements-manifest/analyzer/index.js:78
      fs.writeFileSync(`${process.cwd()}${path.sep}custom-elements.json`, `${JSON.stringify(customElementsManifest, null, 2)}\n`);
                                                                                  ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'SourceFileObject'
    |     property 'statements' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'NodeObject'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at run (file:///C:/code/zywave/custom-element-viewer/node_modules/@custom-elements-manifest/analyzer/index.js:78:83)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async file:///C:/code/zywave/custom-element-viewer/node_modules/@custom-elements-manifest/analyzer/index.js:85:5
</details>

**Expected behavior**
I'd expect for the custom element manifest JSON file to generate.

**Reproduction**
[Repro](https://custom-elements-manifest.netlify.app/?source=aW1wb3J0IHsgaHRtbCwgTGl0RWxlbWVudCwgbm90aGluZyB9IGZyb20gImxpdCI7CmltcG9ydCB7IGN1c3RvbUVsZW1lbnQsIHByb3BlcnR5IH0gZnJvbSAibGl0L2RlY29yYXRvcnMuanMiOwppbXBvcnQgdHlwZSB7IFByb3BlcnR5VmFsdWVzIH0gZnJvbSAibGl0IjsKaW1wb3J0IHR5cGUgewogIENsYXNzTWVtYmVyLAogIEN1c3RvbUVsZW1lbnQsCiAgQ3VzdG9tRWxlbWVudERlY2xhcmF0aW9uLAogIEN1c3RvbUVsZW1lbnRFeHBvcnQsCiAgUGFja2FnZSwKfSBmcm9tICJjdXN0b20tZWxlbWVudHMtbWFuaWZlc3Qvc2NoZW1hIjsKCmZ1bmN0aW9uIHB1YmxpY01lbWJlcnNGaWx0ZXIoY2xhc3NNZW1iZXI6IENsYXNzTWVtYmVyKSB7CiAgcmV0dXJuICghY2xhc3NNZW1iZXIucHJpdmFjeSB8fCBjbGFzc01lbWJlci5wcml2YWN5ID09PSAicHVibGljIikgJiYgIWNsYXNzTWVtYmVyLm5hbWUuc3RhcnRzV2l0aCgiXyIpOwp9CgovKioKICogQW4gZWxlbWVudCB0aGF0IGhlbHBzIHRvIHJlbmRlciBkb2N1bWVudGF0aW9uIGZvciBjdXN0b20gZWxlbWVudHMgYmFzZWQgb24gdGhlIGN1c3RvbSBlbGVtZW50IG1hbmlmZXN0IHNjaGVtYToge0BsaW5rIGh0dHBzOi8vZ2l0aHViLmNvbS93ZWJjb21wb25lbnRzL2N1c3RvbS1lbGVtZW50cy1tYW5pZmVzdC99CiAqLwpAY3VzdG9tRWxlbWVudCgiY3VzdG9tZWxlbWVudC1zY2hlbWEtdmlld2VyIikKZXhwb3J0IGNsYXNzIEN1c3RvbUVsZW1lbnRTY2hlbWFWaWV3ZXJFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7CiAgLyoqCiAgICogQW55IHZhbGlkIHBhdGggdG8gbG9hZCBhIEpTT04gZmlsZSB0aGF0IGFkaGVyZXMgdG8gdGhlIGN1c3RvbSBlbGVtZW50IG1hbmlmZXN0IHNjaGVtYToge0BsaW5rIGh0dHBzOi8vZ2l0aHViLmNvbS93ZWJjb21wb25lbnRzL2N1c3RvbS1lbGVtZW50cy1tYW5pZmVzdC99CiAgICovCiAgQHByb3BlcnR5KHsgdHlwZTogU3RyaW5nIH0pCiAgc3JjOiBzdHJpbmcgfCBudWxsID0gbnVsbDsKCiAgLyoqCiAgICogQW4gb3B0aW9uYWwgc3RyaW5nIGFycmF5IG9mIGVsZW1lbnQgdGFnIG5hbWVzIHRvIHJlbmRlcjsgaWYgbm90IHNldCwgd2lsbCByZW5kZXIgYWxsIGN1c3RvbSBlbGVtZW50cyBpbiB0aGUgc2NoZW1hCiAgICovCiAgQHByb3BlcnR5KHsgdHlwZTogQXJyYXkgfSkKICBlbGVtZW50cz86IHN0cmluZ1tdIHwgbnVsbCA9IG51bGw7CgogIC8qKgogICAqIEFuIG9wdGlvbmFsIHN0cmluZyB0byBwcmVzZWxlY3QgdGhlIGZpcnN0IGVsZW1lbnQgYnkgdGFnIG5hbWUgdG8gcmVuZGVyIG9uIGxvYWQ7IGlmIG5vdCBzZXQsIHdpbGwgc2VsZWN0IHRoZSBmaXJzdCBlbGVtZW50IGluIHRoZSBzY2hlbWEsIGFscGhhYmV0aWNhbGx5IHNvcnRlZAogICAqLwogIEBwcm9wZXJ0eSh7IHR5cGU6IFN0cmluZywgYXR0cmlidXRlOiAiaW5pdGlhbC1lbGVtZW50IiB9KQogIGluaXRpYWxFbGVtZW50OiBzdHJpbmcgfCBudWxsID0gbnVsbDsKCiAgI2lzTG9hZGluZyA9IGZhbHNlOwogICNzY2hlbWE%2FOiBQYWNrYWdlOwogIC8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZSBuby11bmRlZgogICNpbnRlcm5hbHM%2FOiBFbGVtZW50SW50ZXJuYWxzOwoKICBnZXQgI2N1c3RvbUVsZW1lbnREZWZpbml0aW9ucygpIHsKICAgIGlmICh0aGlzLiNzY2hlbWEpIHsKICAgICAgY29uc3QgY3VzdG9tRWxlbWVudEV4cG9ydHMgPSAodGhpcy4jc2NoZW1hLm1vZHVsZXMKICAgICAgICAuZmxhdE1hcCgoeCkgPT4geC5leHBvcnRzKQogICAgICAgIC5maWx0ZXIoKHgpID0%2BIHg%2FLmtpbmQgPT09ICJjdXN0b20tZWxlbWVudC1kZWZpbml0aW9uIikgPz8gW10pIGFzIEN1c3RvbUVsZW1lbnRFeHBvcnRbXTsKCiAgICAgIGNvbnN0IGFyciA9IFtdOwogICAgICBmb3IgKGNvbnN0IGNlIG9mIGN1c3RvbUVsZW1lbnRFeHBvcnRzKSB7CiAgICAgICAgaWYgKHRoaXMuZWxlbWVudHMgJiYgIXRoaXMuZWxlbWVudHMuaW5jbHVkZXMoY2UubmFtZSkpIHsKICAgICAgICAgIGNvbnRpbnVlOwogICAgICAgIH0KICAgICAgICBjb25zdCBjb250YWluaW5nTW9kdWxlID0gdGhpcy4jc2NoZW1hLm1vZHVsZXMuZmluZCgoeCkgPT4geC5wYXRoID09PSBjZS5kZWNsYXJhdGlvbi5tb2R1bGUpOwogICAgICAgIGlmIChjb250YWluaW5nTW9kdWxlKSB7CiAgICAgICAgICBjb25zdCBjbGFzc0RlZiA9IGNvbnRhaW5pbmdNb2R1bGUuZGVjbGFyYXRpb25zPy5maW5kKCh4KSA9PiB4LmtpbmQgPT09ICJjbGFzcyIpOwogICAgICAgICAgaWYgKGNsYXNzRGVmKSB7CiAgICAgICAgICAgIGFyci5wdXNoKHsKICAgICAgICAgICAgICBuYW1lOiBjZS5uYW1lLAogICAgICAgICAgICAgIGRlY2xhcmF0aW9uOiBjbGFzc0RlZiBhcyBDdXN0b21FbGVtZW50RGVjbGFyYXRpb24gJiBDdXN0b21FbGVtZW50LAogICAgICAgICAgICB9KTsKICAgICAgICAgIH0KICAgICAgICB9CiAgICAgIH0KCiAgICAgIHJldHVybiBhcnIuc29ydCgoYSwgYikgPT4gYS5uYW1lLmxvY2FsZUNvbXBhcmUoYi5uYW1lKSk7CiAgICB9CiAgICByZXR1cm4gW107CiAgfQoKICBjb25zdHJ1Y3RvcigpIHsKICAgIHN1cGVyKCk7CgogICAgaWYgKHRoaXMuYXR0YWNoSW50ZXJuYWxzKSB7CiAgICAgIHRoaXMuI2ludGVybmFscyA9IHRoaXMuYXR0YWNoSW50ZXJuYWxzKCk7CiAgICB9CiAgfQoKICBmaXJzdFVwZGF0ZWQoY2hhbmdlZFByb3BzOiBQcm9wZXJ0eVZhbHVlcykgewogICAgc3VwZXIuZmlyc3RVcGRhdGVkKGNoYW5nZWRQcm9wcyk7CgogICAgaWYgKCF0aGlzLiNpc0xvYWRpbmcgJiYgIXRoaXMuI3NjaGVtYSAmJiB0aGlzLnNyYykgewogICAgICB0aGlzLiNsb2FkU2NoZW1hKCk7CiAgICB9CiAgfQoKICB1cGRhdGUoY2hhbmdlZFByb3BzOiBQcm9wZXJ0eVZhbHVlcykgewogICAgc3VwZXIudXBkYXRlKGNoYW5nZWRQcm9wcyk7CgogICAgaWYgKGNoYW5nZWRQcm9wcy5oYXMoInNyYyIpKSB7CiAgICAgIHRoaXMuI2xvYWRTY2hlbWEoKTsKICAgIH0KICB9CgogIHJlbmRlcigpIHsKICAgIHJldHVybiBodG1sYEhlbGxvIHdvcmxkYDsKICB9CgogIGFzeW5jICNsb2FkU2NoZW1hKCkgewogICAgaWYgKHRoaXMuc3JjKSB7CiAgICAgIHRoaXMuI2lzTG9hZGluZyA9IHRydWU7CiAgICAgIHRoaXMuI2ludGVybmFscz8uc3RhdGVzPy5hZGQoIi0tbG9hZGluZyIpOwogICAgICBjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKHRoaXMuc3JjKTsKICAgICAgaWYgKHJlc3BvbnNlLm9rKSB7CiAgICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTsKICAgICAgICB0aGlzLiNzY2hlbWEgPSBkYXRhIGFzIFBhY2thZ2U7CiAgICAgICAgdGhpcy4jYWN0aXZlRWxlbWVudE5hbWUgPSB0aGlzLmluaXRpYWxFbGVtZW50ID8%2FIHRoaXMuI2N1c3RvbUVsZW1lbnREZWZpbml0aW9uc1swXT8ubmFtZTsKICAgICAgICB0aGlzLnJlcXVlc3RVcGRhdGUoKTsKICAgICAgfSBlbHNlIHsKICAgICAgICB0aGlzLiNmYWlsZWRMb2FkID0gdHJ1ZTsKICAgICAgfQogICAgICB0aGlzLiNpc0xvYWRpbmcgPSBmYWxzZTsKICAgICAgdGhpcy4jaW50ZXJuYWxzPy5zdGF0ZXM%2FLnJlbW92ZSgiLS1sb2FkaW5nIik7CiAgICB9CiAgfQp9CgpkZWNsYXJlIGdsb2JhbCB7CiAgaW50ZXJmYWNlIEhUTUxFbGVtZW50VGFnTmFtZU1hcCB7CiAgICAiY3VzdG9tZWxlbWVudC1zY2hlbWEtdmlld2VyIjogQ3VzdG9tRWxlbWVudFNjaGVtYVZpZXdlckVsZW1lbnQ7CiAgfQp9Cg%3D%3D&library=litelement)

[custom element manifest bug.txt](https://github.com/open-wc/custom-elements-manifest/files/6681042/custom.element.manifest.bug.txt)

**Comment by thepassle** [comment]
Seems to be a problem with the following comment:
```
Any valid path to load a JSON file that adheres to the custom element manifest schema: {@link https://github.com/webcomponents/custom-elements-manifest/}
```

Removing this stops it from crashing. :
```
 {@link https://github.com/webcomponents/custom-elements-manifest/}
```

Definitely a bug, not sure why this is happening exactly yet. I'll take a look and debug it.

Minimal repro:
```js

@customElement("customelement-schema-viewer")
export class CustomElementSchemaViewerElement extends LitElement {
  /**
   * Any valid path to load a JSON file that adheres to the custom element manifest schema: {@link https://github.com/webcomponents/custom-elements-manifest/}
   */
  src;
}

```

**Comment by thepassle** [comment]
This should be fixed in https://github.com/open-wc/custom-elements-manifest/commit/03ade50e1db83c7cd6b946a7754dbb6bd6550f7f

Furthermore, I'd love to see the `customelement-schema-viewer` component when it's done 😄  Please do share it with us!
