### ISSUE TITLE
Support output path flag for analyzer

### ISSUE THREAD

**Issue by juliexiong** [open-wc/custom-elements-manifest#36]
`custom-elements-manifest/analyzer` automatically outputs the schema file `custom-elements.json` into whichever directory you run the analyzer, but I'd like to be able to specify a path for the file to output into.

For example, I have a package called `foo-button`. When analyzing files inside `/foo-button/src/`, I want `custom-elements.json` to output into `/foo-button/dist/` instead of in the current directory `/foo-button/`:
```
foo-button/
├── dist/
│   ├── custom-elements.json
├── src/
│   ├── foo-button.ts
│   ├── foo-button-dropdown.ts
│   ├── foo-button-group.ts
│   ├── index.ts
├── package.json
```

Here's the script I'm using to analyze files in `/foo-button/`:
```cmd
cem analyze --globs "./src/foo-*.ts" --litelement
```

Would like a flag like this to specify output path:
```cmd
cem analyze --globs "./src/foo-*.ts" --litelement --out "./dist/"
```

Thanks!

**Comment by thepassle** [comment]
Yeah I think we can make this customizable. I'll take a look at this tomorrow

**Comment by thepassle** [comment]
Added this as `outdir` option in the CLI (e.g.: `cem analyze --outdir dist`). Will release version 0.3.3 shortly
