### ISSUE TITLE
JSDoc description for `@prop` with a `- ` prefix

### ISSUE THREAD

**Issue by hsablonniere** [open-wc/custom-elements-manifest#38]
Hey team :wink:,

I'm used to write my JSDoc like this:

```
@prop {String} foobar - My awesome description
```

This is how it's documented on [JSDoc](https://jsdoc.app/tags-property.html) and how I used it with WCA.

As you can see in this:

https://custom-elements-manifest.netlify.app/?source=LyoqCiAqIEhlbGxvCiAqIAogKiBAcHJvcCB7U3RyaW5nfSBmb29iYXIgLSBNeSBhd2Vzb21lIGRlc2NyaXB0aW9uCiAqLwpleHBvcnQgY2xhc3MgTXlDb21wb25lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHsKCiAgc3RhdGljIGdldCBwcm9wZXJ0aWVzICgpIHsKICAgIHJldHVybiB7CiAgICAgIGZvb2JhcjogeyB0eXBlOiBTdHJpbmcgfSwKICAgIH07CiAgfQp9Cgp3aW5kb3cuY3VzdG9tRWxlbWVudHMuZGVmaW5lKCdteS1jb21wb25lbnQnLCBNeUNvbXBvbmVudCk7&library=litelement

CEM generates a JSON with:

```
"members": [
  {
    "type": {
      "text": "String"
    },
    "description": "- My awesome description",
    "name": "foobar",
    "kind": "field",
    "privacy": "public"
  }
]
```

I think I expected it not to take the `- `.

* What do you think?
* Is it something that needs to be fixed?
* Maybe I'm the one not properly using JSDoc.

**Comment by hsablonniere** [comment]
I would be intrigued to try a PR if you decide CEM needs to handle this.

**Comment by thepassle** [comment]
As discussed on Slack: Youre not _wrong_, but this is how TS gives us the jsdoc description (including the `- `), i kind of was hoping not to have to do any normalizing here because it gets iffy really quickly. If there is enough interest from more people, we should take a look at fixing this though. For now I'd recommend using a custom plugin to remove them.

**Comment by hsablonniere** [comment]
Fair enough, let's do it like this.

**Comment by thepassle** [comment]
I have been sufficiently persuaded 😆 This has been added to the latest version.

@hsablonniere this means you can remove your custom plugin in clever cloud :)

**Comment by hsablonniere** [comment]
:tada: This is awesome!
