### ISSUE TITLE
`--outdir` file path not reflected in `package.json`

### ISSUE THREAD

**Issue by juliexiong** [open-wc/custom-elements-manifest#40]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

**Bug**
I set the output directory for my manifest file to `/dist/`, but it is not reflected in `package.json` after running `cem analyze` script.

**Expected behavior**
I expect that if I set `--outdir` to `dist` in the script, `--outdir` will be reflected in `package.json`:

Command:
```cmd
cem analyze --globs src/foo-*.ts --litelement --outdir dist
```

`package.json`:
```json
{
  "name": "foo-button",
  "customElements": "dist/custom-elements.json"
}
```

**Comment by thepassle** [comment]
Ugh, sorry about that. I had the feeling I'd forgotten something. Should be fixed in 0.3.4, thanks for reporting!

**Comment by juliexiong** [comment]
> 
> 
> Ugh, sorry about that. I had the feeling I'd forgotten something. Should be fixed in 0.3.4, thanks for reporting!

Haha, no worries. Greatly appreciate how fast you address issues!

Unfortunately, this fix is outputting the path as `"customElements": "dist\\custom-elements.json"` instead of `"customElements": "dist/custom-elements.json"`

**Comment by thepassle** [comment]
Thats weird, which command are you running and which OS are you on?

I just call path.join on whatever the outdir is and 'custom-elements.json'

**Comment by juliexiong** [comment]
Yeah, I was looking at the changes you made and it shouldn't have affected the output. Strange.

I'm on Windows 10 Enterprise, and running the command via a node script in my `package.json`:

`package.json`:
```json
{
   "devDependencies": {
      "@custom-elements-manifest/analyzer": "^0.3.4"
  },
  "scripts": {
    "analyze": "cem analyze --globs src/zui-*.ts --litelement --outdir dist"
  }
}
```

Command I run:
```cmd
yarn run analyze
```

Output:
```json
{
   "devDependencies": {
      "@custom-elements-manifest/analyzer": "^0.3.4"
  },
  "scripts": {
    "analyze": "cem analyze --globs src/zui-*.ts --litelement --outdir dist"
  },
  "customElements": "dist\\custom-elements.json"
}
```

Must be a Windows thing?

**Comment by thepassle** [comment]
Hm, looks like I might have to `path.normalize()` the path, which turns it into `dist\custom-elements.json`, which would be the expected path for windows right?

Also, does the actual json file get output to the dist folder correctly?

**Comment by juliexiong** [comment]
Yeah, that sounds right to me. And yep, `custom-elements.json` outputs into the `dist` folder as specified with `--outdir dist`!
