### ISSUE TITLE
TypeScript error: "tagName" does not exist in type 'ClassDeclaration'

### ISSUE THREAD

**Issue by nolanlawson** [open-wc/custom-elements-manifest#43]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

In the playground (or command line), use this custom element:

```js
class MyElement extends HTMLElement {}
customElements.define("my-element", MyElement)
```

You'll get this JSON:

<details><summary>click to expand</summary>

```json
{
  "schemaVersion": "1.0.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "src/my-element.js",
      "declarations": [
        {
          "kind": "class",
          "description": "",
          "name": "MyElement",
          "superclass": {
            "name": "HTMLElement"
          },
          "tagName": "my-element",
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "custom-element-definition",
          "name": "my-element",
          "declaration": {
            "name": "MyElement",
            "module": "src/my-element.js"
          }
        }
      ]
    }
  ]
}
```

</details>

If you compare this to the [schema](https://github.com/webcomponents/custom-elements-manifest/blob/2e391f2993431c231c4d2f34ce6d2f1d24ddad69/schema.d.ts), it doesn't match because of `tagName` on the `ClassDeclaration`.

You can repro using a simple TypeScript file:

<details><summary>click to expand</summary>

```ts
import { Package } from 'custom-elements-manifest/schema'

const json: Package = {
  "schemaVersion": "1.0.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "index.js",
      "declarations": [
        {
          "kind": "class",
          "description": "",
          "name": "MyElement",
          "superclass": {
            "name": "HTMLElement"
          },
          "tagName": "my-element",
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "custom-element-definition",
          "name": "my-element",
          "declaration": {
            "name": "MyElement",
            "module": "index.js"
          }
        }
      ]
    }
  ]
}
```

</details>

Then run:

```shell
mkdir test
cd test
npm init --yes
npm i --save custom-elements-manifest@1.0.0 typescript@4.3.4
npx tsc index.ts
```

You'll see the error:

```
test.ts:18:11 - error TS2322: Type '{ kind: "class"; description: string; name: string; superclass: { name: string; }; tagName: string; customElement: true; }' is not assignable to type 'Declaration'.
  Object literal may only specify known properties, and '"tagName"' does not exist in type 'ClassDeclaration'.

18           "tagName": "my-element",
             ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Expected behavior**

The output schema should match the one from `custom-elements-manifest `.

I'm not sure if this is a problem in the analyzer or in the `custom-elements-manifest` schema itself, but I'm just reporting it.

**Comment by thepassle** [comment]
This seems like a bug in the schema. A custom element has a tagname: https://github.com/webcomponents/custom-elements-manifest/blob/master/schema.d.ts#L198 so the output JSON in this case is correct. Looks like this is the offender though: https://github.com/webcomponents/custom-elements-manifest/blob/master/schema.d.ts#L71

Would you mind creating an issue in https://github.com/webcomponents/custom-elements-manifest ?

**Comment by thepassle** [comment]
As for some of your comments in your PR, it is still early days for `custom-elements.json`, we only recently released the V1 version and tooling hasnt caught up yet, but we're actively working on these things. There's an open issue for [api-viewer](https://github.com/web-padawan/api-viewer-element/issues/61), as well as a PR for [Storybook](https://github.com/storybookjs/storybook/pull/15138) to support the latest version of the schema, and hopefully more tooling will start to support CEM soon as well 🙂

**Comment by nolanlawson** [comment]
No problem. Opened an issue here: https://github.com/webcomponents/custom-elements-manifest/issues/69

And thanks, I understand it's early days for `custom-elements.json`. I appreciate the hard work you're putting into this. It's unglamorous standardization work, it's hard to move a big ecosystem (like herding cats!), but it's much needed, so thank you for putting in the effort. :slightly_smiling_face:

**Comment by thepassle** [comment]
Great, ill close this issue then - lets continue discussion in the other repo. Thanks!
