### ISSUE TITLE
Tagname not getting populated if the class is a default export

### ISSUE THREAD

**Issue by Matsuuu** [open-wc/custom-elements-manifest#52]
**Checklist**
- [X] Did you run the analyzer with the `--dev` flag to get more information?
- [X] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

https://custom-elements-manifest.netlify.app/?source=CmV4cG9ydCBkZWZhdWx0IGNsYXNzIE15RWxlbWVudCBleHRlbmRzIEhUTUxFbGVtZW50IHsKICBmb28gPSAnaGVsbG8nOwoKICAvKioKICAgKiBAYmFyIHRoaXMgaXMgY3VzdG9tIGluZm9ybWF0aW9uCiAgICovCiAgbWVzc2FnZTsKfQoKY3VzdG9tRWxlbWVudHMuZGVmaW5lKCJteS1lbGVtZW50IiwgTXlFbGVtZW50KTs%3D&library=null

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**
The `link-class-to-tagname.js` post process should link tagnames if they are not documented.

However theres a bug in the system currently which names the class "default" if it's default exported
e.g.

```
export default class MyComponent extends HTMLElement {

}
```

Which therefore breaks the linking process

**Comment by thepassle** [comment]
this was fixed and is available in the latest version
