### ISSUE TITLE
`#private` fields should not inherit

### ISSUE THREAD

**Issue by bennypowers** [open-wc/custom-elements-manifest#57]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

https://custom-elements-manifest.netlify.app/?source=CmV4cG9ydCBjbGFzcyBBIGV4dGVuZHMgSFRNTEVsZW1lbnQgewogICNwcml2YXRlID0gJ2hlbGxvJzsKICBwcml2YXRlIHByaXYgPSAnaGVsbG8nOwp9CgpleHBvcnQgY2xhc3MgQiBleHRlbmRzIEEgewp9&library=null

**Source**
```js
export class A extends HTMLElement {
  #private = 'hello';
  private priv = 'hello';
}

export class B extends A {
}
```
**Expected behavior**
`#private` and `priv` should not inherit to B, the first because it's a runtime error, the second because it's a TypeScript error.
**Actual**
```json
{
  "kind": "class",
  "description": "",
  "name": "B",
  "superclass": {
    "name": "A",
    "module": "src/my-element.js"
  },
  "members": [
    {
      "kind": "field",
      "name": "#private",
      "privacy": "private",
      "type": {
        "text": "string"
      },
      "default": "'hello'",
      "inheritedFrom": {
        "name": "A",
        "module": "src/my-element.js"
      }
    },
    {
      "kind": "field",
      "name": "priv",
      "type": {
        "text": "string"
      },
      "privacy": "private",
      "default": "'hello'",
      "inheritedFrom": {
        "name": "A",
        "module": "src/my-element.js"
      }
    }
  ]
}
```

**Comment by thepassle** [comment]
I'm not sure if this would really be the "correct" behavior, while you cant interact with private properties, `class B` _does_ inherit them from `class A`

![image](https://user-images.githubusercontent.com/17054057/123979609-29e94100-d9c1-11eb-87d1-e7647c10ecae.png)

**Comment by bennypowers** [comment]
hmm interesting
yeah that's confusing as heck :D

guess could leave it then
