### ISSUE TITLE
Litelement properties initialized with an imported value does not have type or default value defined

### ISSUE THREAD

**Issue by Niznikr** [open-wc/custom-elements-manifest#60]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [x] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**
Properties of a lit component that get initialized from an imported module ([here's an example](https://github.com/ithaka/pharos/blob/develop/packages/pharos/src/components/layout/pharos-layout.ts#L50)) do not have a type or default value defined in the manifest (in this case it would be `string` and `3.5rem`). This was working correctly with `web-component-analyzer`.

**Comment by thepassle** [comment]
Could you provide a minimal reproduction? Its not entirely clear to me what you're importing and expecting to be output

**Comment by thepassle** [comment]
Could you provide a minimal reproduction? Its not entirely clear to me what you're importing and expecting to be output

**Comment by Niznikr** [comment]
[Here's the best I can do](https://custom-elements-manifest.netlify.app/?source=CmltcG9ydCB7IExpdEVsZW1lbnQgfSBmcm9tICdsaXQtZWxlbWVudCc7Cgpjb25zdCBURVNUX1ZBTFVFID0gJ2hlbGxvJzsKCmV4cG9ydCBjbGFzcyBNeUVsZW1lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHsKICBzdGF0aWMgZ2V0IHByb3BlcnRpZXMoKSB7CiAgICByZXR1cm4gewogICAgICBmb286IHsgdHlwZTogU3RyaW5nIH0KICAgIH0KICB9CgogIGNvbnN0cnVjdG9yKCkgewogICAgc3VwZXIoKTsKICAgIHRoaXMuZm9vID0gVEVTVF9WQUxVRTsKICB9CgogIG15TWV0aG9kKCl7fQp9Cg%3D%3D&library=litelement) (not sure how to include an another file in the playground). You can assume TEST_VALUE is imported from a separate JS/TS file.

**Comment by Niznikr** [comment]
In that example I'd expect `foo` to have `"type": {"text": "string"}` and `"default": "'hello'"`

**Comment by thepassle** [comment]
Just as an update, I'm working on this in https://github.com/open-wc/custom-elements-manifest/pull/69

It should be mostly done, but i'd like to take some more time to iron out the edge cases.

**Comment by thepassle** [comment]
This should be fixed in 0.4.8 🙂
