### ISSUE TITLE
LitElement resolveInitializer module path mismatch

### ISSUE THREAD

**Issue by Niznikr** [open-wc/custom-elements-manifest#83]
**Checklist**
- [x] Did you run the analyzer with the `--dev` flag to get more information?
- [ ] Did you create a **minimal** reproduction in the [playground](https://custom-elements-manifest.netlify.app/)?

Completing the items above will greatly improve triaging time of your issue.

**Expected behavior**
When importing a module from another file to initialize a property, the resulting `resolveInitializer` field with `module` path does not match the path of the actual module resulting in the property's `default` value not getting extracted from the module. [Here is a simple repo](https://github.com/Niznikr/custom-elements-manifest-default-repro) reproducing the issue. The prop [here](https://github.com/Niznikr/custom-elements-manifest-default-repro/blob/main/src/components/button.ts#L11) is initialized to a value from an imported module. In the generated manifest, [the property's](https://github.com/Niznikr/custom-elements-manifest-default-repro/blob/main/custom-elements.json#L42) `default` field is set to `ColorRed` instead of the expected `'#FF0000'`. This is because `module` in `resolveInitializer` found [here](https://github.com/Niznikr/custom-elements-manifest-default-repro/blob/main/custom-elements.json#L52) is set to `/src/tokens/colors` while the module's path in the manifest is equal to `src/tokens/colors.ts` found [here](https://github.com/Niznikr/custom-elements-manifest-default-repro/blob/main/custom-elements.json#L7) and so the expected default value is not extracted.

**Comment by Niznikr** [comment]
More than happy to reproduce in the playground if there's a way to add an additional file there.

**Comment by thepassle** [comment]
Sorry for the slow reply 🙂  The repro you made is super helpful, just havent had the time to get to this yet. I hope to have some more time by the end of this week.

**Comment by Niznikr** [comment]
No worries @thepassle! Thanks for the reply.

**Comment by thepassle** [comment]
this should be fixed in https://github.com/open-wc/custom-elements-manifest/pull/109
