### ISSUE TITLE
Issue with JSDoc's @link tag

### ISSUE THREAD

**Issue by peschee** [open-wc/custom-elements-manifest#98]
# Playground issue

Reproduction URL: 
https://custom-elements-manifest.netlify.app/?source=Ci8qKgogKiBbbGlua117QGxpbmsgaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbX0uCiAqLwpjbGFzcyBNeUVsZW1lbnQgZXh0ZW5kcyBIVE1MRWxlbWVudCB7CiAgc3RhdGljIGdldCBvYnNlcnZlZEF0dHJpYnV0ZXMoKSB7CiAgICByZXR1cm4gWydkaXNhYmxlZCddOwogIH0KCiAgc2V0IGRpc2FibGVkKHZhbCkgewogICAgdGhpcy5fX2Rpc2FibGVkID0gdmFsOwogIH0KICBnZXQgZGlzYWJsZWQoKSB7CiAgICByZXR1cm4gdGhpcy5fX2Rpc2FibGVkOwogIH0KCiAgZmlyZSgpIHsKICAgIHRoaXMuZGlzcGF0Y2hFdmVudChuZXcgRXZlbnQoJ2Rpc2FibGVkLWNoYW5nZWQnKSk7CiAgfQp9CgpjdXN0b21FbGVtZW50cy5kZWZpbmUoJ215LWVsZW1lbnQnLCBNeUVsZW1lbnQpOwo%3D&library=null

## Additional information:

The analyzer does not seem to like [JSDoc's @link tag](https://jsdoc.app/tags-inline-link.html)

**Comment by bennypowers** [comment]
🤔 Interesting

What's your expected output?

**Comment by bennypowers** [comment]
Some reference material:

https://jsdoc.app/tags-inline-link.html

Looks like TS's AST doesn't handle them well either

https://astexplorer.net/#/gist/fda1255cf9b907f5c4a4dccd2e6b379e/7b84b423d9e853c2424fb1a8478e89a18bfd22b8

**Comment by thepassle** [comment]
looks like its related to this https://github.com/open-wc/custom-elements-manifest/commit/03ade50e1db83c7cd6b946a7754dbb6bd6550f7f#diff-617a0f945d183ba03903d2e564315b59dba448d3dcb6852137c219e29caa87c8

probably need to add the same handling here 
https://github.com/open-wc/custom-elements-manifest/blob/e6b824a5156281c32d0a2462b48c87cbf8d4fccd/packages/analyzer/src/utils/jsdoc.js#L9-L14

**Comment by peschee** [comment]
> 🤔 Interesting
> 
> What's your expected output?

I would expect it gets ignored and the cem analyzer runs and outputs without errors.
